### ISSUE TITLE
Silicon Dust

### ISSUE THREAD

**Issue by FreddyFroge** [Slomaxonical-907/croptopia-chocolaterie-forge#2]
Hi there!

I have been looking everywhere to contact you, but I cannot find a discord or something like that, so I'm trying here.
I cannot, for the life of me, figure out how to make silicon dust. I may have just overseen something, but I do not know how, nor does the rest of the people I'm playing with.

Would you happen to have a complete crafting list for the mod somewhere?
Thanks in advance!

-Freddy

**Comment by Traehgniw** [comment]
Use some kind of recipe/item list mod like JEI.
(ALso: I think it's quartz and sand.)
