### ISSUE TITLE
Forge 1.19.2 Update

### ISSUE THREAD

**Issue by dagobertdu94** [Slomaxonical-907/croptopia-chocolaterie-forge#3]
I hope you don't mind that I forked your project and updated it myself to Forge 1.19.2.
If you are interested in the updated source code, you will find it here: https://github.com/dagobertdu94/croptopia-chocolaterie-forge_1.19.2

If you compare my master branch with your master branch, you should quickly find my changes to make it compatible with 1.19.2.
If you may have any questions (*or want me to delete it forever*), you can tell me anytime. I will answer as fast as I am able to...

Greetings,
dagobertdu94

PS: Sorry for my bad english...

**Comment by Slomaxonical-907** [comment]
I do not mind, in fact I would love for you to make a pull request to this repo so i can merge your port!

This is great!
PS: English is not my first language as well...

**Comment by dagobertdu94** [comment]
I have opened a pull request.
I have tested it locally and all recipes seems to be present.
If you find anything not working in my 1.19.2 port, you can tell me...

**Comment by Slomaxonical-907** [comment]
merged, thank you G

**Comment by dagobertdu94** [comment]
@Slomaxonical-907 I don't know if it's important but I just added Croptopia in my fork as mandatory dependency.
I know the items may be able exist without Croptopia installed but originally you made the mod as addon for Croptopia so I thought it could be useful if Chocolaterie would require Croptopia.

And I am currently working on an update for MC 1.20.1, you can find it in the same fork in the master branch but please ignore the chaos in the files.
I had some trouble with ForgeGradle and after that with uploading to GitHub...

EDIT: I took a look in the ItemRegistry class and I think it would crash without Croptopia installed, but it would still be better to define Croptopia as dependency instead of causing an exception for which may then an issue be created...
And sorry for my bad english at some points.
